### ISSUE TITLE
[Bug] [Won't fixed] Cypress run keep failing on createBusinessAccount.spec.js

### ISSUE THREAD

**Issue by jmezaber** [kevin-ghannoum/soen490#177] opened 2022-01-17 05:55 UTC
The same spec keeps causing the Cypress run to fail
![](https://media.discordapp.net/attachments/846460712845967360/932506684016959518/Screen_Shot_2022-01-17_at_12.28.29_AM.png)

**Comment by nasaku898** [comment] 2022-01-29 16:25
Wont fixed. After investigation, it is an issue caused by the pipeline delays.

**Closed by nasaku898** 2022-01-29 16:25 UTC
Labels: bug
