### ISSUE TITLE
Make business and industry field optional when creating client account

### ISSUE THREAD

**Issue by nasaku898** [kevin-ghannoum/soen490#89] opened 2021-11-03 00:42 UTC
Adding this to backlog.
From PO comment, we should consider client account as your everyday customer. So business and industry field needs to be optional.
https://github.com/kevin-ghannoum/soen490/issues/72
#72

**Comment by Manraj45** [comment] 2021-12-23 18:45
This issue is a duplicate of #117. Hence, it is being closed.

**Closed by Manraj45** 2021-12-23 18:45 UTC
Labels: task
